### ISSUE TITLE
Wrong management of redirection to a variable.

### ISSUE THREAD

**Issue by rotrojan** [Cyren4/Minishell#69]
![image](https://user-images.githubusercontent.com/52586053/142776974-73a37ecd-f503-45d6-aa53-7a116d65f651.png)
`bash` and `bash --posix` does not behave the same way for this: I think it's ok to choose one or the other ... 🤷

**Comment by VincentBaron** [comment]
Ctte issue est pour toi Il fut comme pour le heredoc stocker la valeur avant expansion et comme ca je checkerai si une expansion a eu lieu et renvoyer le message d erreur si le file est une expansion avec > ou >>
